# 1D Array

In [2]:
import numpy as np


In [3]:
#Creating sample array
arr = np.arange(0,11)    #so arange method can be used to create "1D" array.

In [4]:
#Show
arr   

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr.shape  #shape is attribute

(11,)

In [5]:
#Get a value at an index
arr[8]

8

In [9]:
#Get values in a range
arr[1:5] #5 is nut included just like python

array([1, 2, 3, 4])

In [10]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [16]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100     #this replace 0,1,2,3,4 with 100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [31]:
# Reset array, we'll see why i had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr




array([0, 1, 2, 3, 4, 5])

In [33]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr


array([99, 99, 99, 99, 99, 99])

In [34]:
# Now note the changes also occur in our original array!
arr  #so change done in slice_of_array was transferred to arr also. 

# Data is not copied, it's a view of the original array! This avoids memory problems!



array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [43]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# 2D array

In [6]:
# Indexing a 2D array

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45])) #by adding list we create a 2D array.

#Show
arr_2d



array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [7]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

# Format is :       arr_2d[row][col] 
#                    OR
#               arr_2d[row,col]    we will use this

In [8]:
#2D array indexing: the above syntax is true for indexing not for slicing.

# Getting individual element value
arr_2d[1][0]




20

In [12]:
# Getting individual element value
arr_2d[1,0]    #this is similar to [1][0] in terms of indexing not for slicing.

#this gives same value just like above cell. Many people think that by writing 1,0 we will get row1 and row0 
#but this is not true we get a particular element.

20

In [20]:
# 2D array slicing
#Shape (2,2) from top right corner
arr_2d[:2,1:]

#[:2] means for rows. Starting from beginning(:) till 2(i.e. 0,1 and excluding 2)
#[1:] means for columns.starting from column1(after column0) till end(:)




array([[10, 15],
       [25, 30]])

**in case of slicing the syntax works differently.**

In [21]:
arr_2d[:2][1:]   

array([[20, 25, 30]])

In [22]:
#Shape bottom row
arr_2d[1]    #only first row is considered


array([20, 25, 30])

In [23]:
arr_2d[1:]                             #it means first row and all rows below it.

array([[20, 25, 30],
       [35, 40, 45]])

In [47]:
#Shape bottom row
arr_2d[2,:]                        #it means second row and all columns.

array([35, 40, 45])

In [24]:
#consider another array

final_arr=np.array([[5,10,15,'a'],[20,25,30,'b'],[35,40,45,'c'],[50,55,60,'d']]) 

In [25]:
final_arr

array([['5', '10', '15', 'a'],
       ['20', '25', '30', 'b'],
       ['35', '40', '45', 'c'],
       ['50', '55', '60', 'd']], dtype='<U21')

In [26]:
final_arr[1:3,1:3]

array([['25', '30'],
       ['40', '45']], dtype='<U21')

In [15]:
# Fancy Indexing

#Set up matrix
arr2d = np.zeros((10,10))                       #or np.array(([10,10]))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
#Length of array
arr_length = arr2d.shape[1]  #this returns number of rows which is 10
arr_length

10

In [70]:
#Set up array

for i in range(arr_length):     #so loop runs from 0 to 9
    arr2d[i] = i            #arr[0]=0       so 0 is filled in arr2d[0]
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [71]:
#Fancy indexing allows the following
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [72]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])