In [2]:
import numpy as np

# Universal functions perform operations on all elements in an array

In [4]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#Taking Square Roots
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [8]:
#Calcualting exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [3]:
# Binary Functions require two arrays

#Random array (normal dist)
A = np.random.randn(10)

A


array([ 0.9222777 , -0.25993214,  0.88377813,  1.77602476, -0.48632384,
        0.8374905 , -0.62598522,  0.05648838, -0.36771021, -0.47188977])

In [4]:
#Random array (normal dist)
B = np.random.randn(10)
B

array([-0.24378121,  0.86599649,  0.05214577, -1.26468523, -1.16378888,
        0.69391004,  0.05127715,  1.2426985 , -1.65725504, -1.1387896 ])

In [5]:
#Addition
np.add(A,B)

array([ 0.67849649,  0.60606435,  0.9359239 ,  0.51133953, -1.65011272,
        1.53140054, -0.57470807,  1.29918688, -2.02496525, -1.61067937])

In [6]:
#Finding max or min between two arrays
np.maximum(A,B)

array([ 0.9222777 ,  0.86599649,  0.88377813,  1.77602476, -0.48632384,
        0.8374905 ,  0.05127715,  1.2426985 , -0.36771021, -0.47188977])

In [7]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)  #we will get list of all functions which we can use.

True