In [1]:
# Creating Numpy arrays
import numpy as np

# Converting from a list
#Lets start with a list

my_list1 = [1,2,3,4] 

my_array1 = np.array(my_list1)



In [3]:
#Print out array

my_array1

array([1, 2, 3, 4])

In [6]:
# Make another list
my_list2 = [11,22,33,44]

#Make a list of lists
my_lists = [my_list1,my_list2]

#Make multi-dimensional array
my_array2 = np.array(my_lists)

#Show array
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [29]:
#Lets get the size of the array by using shape method.

my_array2.shape        #hence we have two rows and four columns


(2, 4)

In [33]:

my_array2.shape[0]  #so at index 0 we had two rows

2

In [34]:

my_array2.shape[1]   #so at index 1 we had two columns.

#shape does nottake more values 2,3,4 because it carries only two values.

4

In [10]:
#Find out the data type of objects inside the array
my_array2.dtype   #dtype is attribute in numpy library.

dtype('int64')

In [19]:
#Making special case arrays

#Zeros
np.zeros(5)  #the decimal point with zeroes is because they are of floating type.

array([0., 0., 0., 0., 0.])

In [22]:
#let us verify how they are floating type.

my_zero_array=np.zeros(5)
my_zero_array.dtype

dtype('float64')

In [13]:
#Ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
# An empty array

np.empty(5)


array([0.00000000e+000, 5.30276956e+180, 3.31033942e-033, 6.97935766e-076,
       3.25903115e-086])

In [24]:
np.empty((3,4))

array([[4.67751532e-310, 5.02034658e+175, 2.69609784e+184,
        1.17092500e-046],
       [4.01346371e-057, 6.75801212e-067, 5.01163185e+217,
        5.49419094e-143],
       [9.80058441e+252, 1.30304358e-142, 2.14027814e+161,
        1.50002183e+248]])

In [16]:
#Identity array
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
# Using a range

np.arange(5)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(5,50,2)             #start:stop:step size

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

# You can see that all above methods of numpy produced array.