In [4]:
import numpy as np

In [5]:
5/2

2.5

In [6]:
arr0=np.array([1,2,3])      #this is 1D array

In [7]:
arr0

array([1, 2, 3])

In [8]:
# Create array
arr1 = np.array([[1,2,3],[8,9,10]])  #this is very important. here we have created list within array. ([[]])

#Show
arr1 # a 2D array is created


array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [12]:
arr2= np.array(([23,45,6],[34,54,56]))    #2nd method:here also 2Darray is created by (([]))
arr2 

array([[23, 45,  6],
       [34, 54, 56]])

In [5]:
#Multiplying Arrays
arr1*arr1           #1*1, 2*2, 3*3, 8*8  and so on.

array([[  1,   4,   9],
       [ 64,  81, 100]])

In [6]:
#Subtraction
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [4]:
#Arithmetic operations with scalars on array
1 / arr1        #1/1  1/2  1/3  1/8  1/9  1/10

array([[1.        , 0.5       , 0.33333333],
       [0.125     , 0.11111111, 0.1       ]])

In [5]:
#Exponential operation
arr1 ** 3

array([[   1,    8,   27],
       [ 512,  729, 1000]])